export const storeProducts = [
  {
    id: 1,
    title: "ONYX Faust 3",
    img: "img/product-1.png",
    price: 6599,
    company: "Onyx",
    info: "ONYX BOOX Faust 3 is a device for reading electronic books with an electronic paper 6” E Ink Carta screen and a built-in flicker-free MOON light 2 system with color temperature control. A Wi-Fi module and sensor control together with a pre-installed browser allow the user to surf on the Internet.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "PocketBook 628",
    img: "./img/product-2.png",
    price: 7599,
    company: "PocketBook",
    info: "Thanks to the 6-inch E Ink Carta™ HD screen, intelligent SMARTlight function, and weight of only 155 g, the PocketBook 628 is an excellent choice for those who love to spend every free moment reading comfortably and safely.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "DEXP Moon",
    img: "img/product-3.png",
    price: 5799,
    company: "DEXP",
    info: "DEXP Moon – Now with a 6.8” display and thinner borders, adjustable warm light, up to 10 weeks of battery life, and 20% faster page turns.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Digma M1",
    img: "img/product-4.png",
    price: 7999,
    company: "Digma",
    info: "Digma M1 - Read and Annotate Any File on A5-Size Display. You can annotate and write on 20+ file formats and add bookmarks. With the adjustable front light, you can get the most comfortable view on the 227dpi HD screen in any light.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "PocketBook 633 Color",
    img: "img/product-5.png",
    price: 9699,
    company: "PocketBook",
    info: "Purpose-built for reading: with a flush-front design and 300 ppi glare-free display that reads like real paper, even in bright sunlight.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "DEXP Symbol",
    img: "img/product-6.png",
    price: 5399,
    company: "apple",
    info: "More books in more places: store thousands of titles, then take them all with you. A single charge via USB-C last weeks, not hours. Easy on the eyes: now with adjustable warm light to change screen shade from white to amber.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "ONYX BOOX Volta 3",
    img: "img/product-7.png",
    price: 12999,
    company: "Onyx",
    info: "ONYX BOOX Volta 3 is a device for reading electronic books with an electronic paper 6” E Ink Carta screen and a built-in flicker-free MOON light 2 system with color temperature control. A Wi-Fi module and sensor control together with a pre-installed browser allow the user to surf on the Internet.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Digma K2",
    img: "img/product-8.png",
    price: 7499,
    company: "Digma",
    info: "Adjustable front light lets you read comfortably for hours, indoors and outdoors, day and night. Purpose built for reading, with a 167 ppi glare-free display that reads like printed paper, even in direct sunlight.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
